apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: ARTIFACT_NAME
  namespace: NAMESPACE
  labels:
    app.kubernetes.io/part-of: ARTIFACT_NAME
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/tsalm-pivotal/ARTIFACT_NAME.git
      ref:
        branch: main
  serviceClaims:
  - name: config-server
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: configserver-binding-compatible
  - name: auth-client
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: auth-client
  - name: observability
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ResourceClaim
      name: observability-binding-compatible
  build:
    env:
    - name: BP_JVM_VERSION
      value: JAVA_VERSION